/* Name: Ana Thomas
 * Date: 03/06/17
 * 
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ProjectEuler
{
    class EvenFibonacci
    {
        public void display()
        {
            Console.WriteLine("\n 2. Even Fibonacci \n");
            Console.WriteLine("Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:");
            Console.WriteLine("1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...");
            Console.WriteLine("By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms. \n");

            calc();
        }

        public void calc()
        {
            int a = 0;
            int b = 1;
            int sum = 0;


            for (int i = 0; i < 10; i++)
            {
                int temp = a;
                a = b;
                b = temp + b;
                if (a % 2 == 0)

                    sum = sum + a;
            }
            Console.WriteLine("Total sum: " + sum);
        }
    }
}
